###########################################################
### Welcome to Beautiful Jekyll!
###########################################################

title: MacroData
author: Cristian Román

navbar-links:
  El proyecto: "aboutme"
  Cursos:
    - Fechas: "fechas"
    - Objetivos: "objetivos"
    - Contenidos: "contenidos"
    - Politicas: "politicas"
    - Aplicaciones: "aplicaciones"
  Proyecto final: "proyecto-final"
  Galería: "galerias"
  Logros: "logros"
  Quienes somos: "quienes"

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

favicon: "/assets/img/avatar-icon.png"

social-network-links:
  email: "SI-DSEVO@arizona.edu"

rss-description: This website is a virtual proof that I'm awesome

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
  reddit: false

title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: true

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

site-css:
  - "/assets/css/custom.css"
site-js:
  - "/assets/js/macrodata.js"

date_format: "%B %-d, %Y"

timezone: "America/Phoenix"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
